<a href="https://colab.research.google.com/github/alina518/Projects/blob/main/SimpleRNN(IMDB_Dataset).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [ ]:
#define the vocabulary size
voc_size=10000

In [ ]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1369, 7942, 1143, 8417],
 [1369, 7942, 1143, 4835],
 [1369, 3307, 1143, 3574],
 [1137, 7769, 4750, 5315, 2511],
 [1137, 7769, 4750, 5315, 3469],
 [7435, 1369, 2499, 1143, 2676],
 [1335, 2012, 9975, 5315]]

In [ ]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np
sent_length=8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedding_docs

array([[   0,    0,    0,    0, 1369, 7942, 1143, 8417],
       [   0,    0,    0,    0, 1369, 7942, 1143, 4835],
       [   0,    0,    0,    0, 1369, 3307, 1143, 3574],
       [   0,    0,    0, 1137, 7769, 4750, 5315, 2511],
       [   0,    0,    0, 1137, 7769, 4750, 5315, 3469],
       [   0,    0,    0, 7435, 1369, 2499, 1143, 2676],
       [   0,    0,    0,    0, 1335, 2012, 9975, 5315]], dtype=int32)

In [ ]:
#feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 663ms/step


array([[[ 0.02324844, -0.00735259,  0.01988122, -0.01847444,
          0.03208513, -0.0313762 ,  0.00229786,  0.02914432,
          0.01797691,  0.02184502],
        [ 0.02324844, -0.00735259,  0.01988122, -0.01847444,
          0.03208513, -0.0313762 ,  0.00229786,  0.02914432,
          0.01797691,  0.02184502],
        [ 0.02324844, -0.00735259,  0.01988122, -0.01847444,
          0.03208513, -0.0313762 ,  0.00229786,  0.02914432,
          0.01797691,  0.02184502],
        [ 0.02324844, -0.00735259,  0.01988122, -0.01847444,
          0.03208513, -0.0313762 ,  0.00229786,  0.02914432,
          0.01797691,  0.02184502],
        [ 0.03041241,  0.04679299,  0.0086895 , -0.01456577,
         -0.03933275,  0.02653018,  0.04415325,  0.00836803,
         -0.03014883,  0.01182485],
        [-0.00212821,  0.0475519 ,  0.01937601,  0.0104921 ,
         -0.025413  ,  0.03897134,  0.01014578,  0.04074702,
         -0.02951275,  0.01863999],
        [-0.02715855,  0.02657335,  0.00385524, -0.0

# **End to End Deep Learning Project Using RNN**

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [ ]:
## load the dataset
max_features=10000 #vocabulary size
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=max_features)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(25000,)
(25000,)
(25000,)
(25000,)


In [ ]:
y_train[0]

np.int64(1)

In [ ]:
#inspect sample review and its label
sample_review=x_train[0]
print(sample_review)
sample_label=y_train[0]
print('Sample Label: ',sample_label)

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Sample Label:  1


In [ ]:
#mapping of words index back to words(for understanding)
word_index=imdb.get_word_index()


1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
reverse_word_index={value:key for key,value in word_index.items()}
reverse_word_index

{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [ ]:
decoded_review=' '.join([reverse_word_index.get(i-3, '?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [ ]:
max_len=500
x_train=sequence.pad_sequences(x_train,maxlen=max_len)
x_test=sequence.pad_sequences(x_test,maxlen=max_len)
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [ ]:
#training simple rnn
model=Sequential()
model.add(Embedding(max_features,128,input_length=max_len))
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#create an instance of early stopping callback
from tensorflow.keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
early_stopping

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

history=model.fit(
    x_train,y_train,epochs=10,batch_size=32,
    validation_split=0.2,
    callbacks=early_stopping
)


Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 29s 42ms/step - accuracy: 0.6413 - loss: 0.8475 - val_accuracy: 0.6974 - val_loss: 0.5653
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.8007 - loss: 0.4448 - val_accuracy: 0.7746 - val_loss: 0.4681
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.8668 - loss: 0.3148 - val_accuracy: 0.7958 - val_loss: 0.4552
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.8188 - loss: 0.4088 - val_accuracy: 0.7686 - val_loss: 0.5226
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 42ms/step - accuracy: 0.8945 - loss: 0.2641 - val_accuracy: 0.7432 - val_loss: 0.5820
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.8942 - loss: 0.2626 - val_accuracy: 0.7624 - val_loss: 0.5830
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.9147 - loss: 0.2150 - val_accuracy: 0.7766 - val_loss: 0.5980
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 41ms/step - accuracy: 0.9378 - loss: 0.1573 - 

In [ ]:
#save model file
model.save('simple_rnn_imdb.h5')

**Using the saved model**

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [ ]:
word_index=imdb.get_word_index()
reverse_word_index={value:key for key,value in word_index.items()}

In [ ]:
model=load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (32, 500, 128)         │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (32, 128)              │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (32, 1)                │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [ ]:
#helper functions to decode the reviews
def decode_review(encoded_review):
  return ' '.join(reverse_word_index.get(i-3,'?') for i in encoded_review)

#function to preprocess user input-padding
def preprocess_text(text):
  words=text.lower().split()
  encoded_review=[word_index.get(word,2)+3 for word in words]
  padded_review=sequence.pad_sequences([encoded_review],maxlen=500)
  return padded_review

In [ ]:
#prediction function
def predict_sentiment(review):
  preprocessed=preprocess_text(review)
  prediction=model.predict(preprocessed)
  sentiment='Positive' if prediction[0][0]>0.5 else 'Negative'
  return sentiment,prediction[0][0]

In [ ]:
#user input and prediction
example_review='This movie was really good! The plot was amazing and the acting was crazy good!'
sentiment,score=predict_sentiment(example_review)
print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 452ms/step
Review: This movie was really good! The plot was amazing and the acting was crazy good!
Sentiment: Positive
Prediction Score: 0.7016738653182983
